### ISSUE TITLE
Clarification on Confluent Connect Hub Documentation

### ISSUE THREAD

**Issue by WillemSF2A** [jcustenborder/kafka-connect-redis#11]
@jcustenborder  The message says `A Kafka Connect connector receiving data from redis.` But based on a quick look at the source code here, it's a sink connector and not a source connector.  Can you confirm this statement on Connect Hub is in error?

https://www.confluent.io/connector/kafka-connect-redis/

**Comment by jcustenborder** [comment]
@WillemSF2A Sorry about the confusion. This connector in it's current state will write data to redis. It will have support soon to pull data as well.

**Comment by WillemSF2A** [comment]
@jcustenborder Thanks.  I'm good with this explanation.  Will watch given the place where I work might be quite interested in using this connector once the read capabilities are available.
