### ISSUE TITLE
Test the connection

### ISSUE THREAD

**Issue by mostafaghadimi** [jcustenborder/kafka-connect-redis#13]
Hi @jcustenborder and @mayankdang 

Would you please add some examples to test the sink connection between Kafka and Redis in docker? (In other words create some data in kafka topics and then write them in Redis)

Thanks,
Mostafa

**Comment by jcustenborder** [comment]
@mostafaghadimi Take a look at [bin](https://github.com/jcustenborder/kafka-connect-redis/tree/master/bin) and [config](https://github.com/jcustenborder/kafka-connect-redis/tree/master/config). This is what I use for development.
