### ISSUE TITLE
Writing sets to Redis

### ISSUE THREAD

**Issue by pavlepiramida** [jcustenborder/kafka-connect-redis#16]
I have a question,since Im still pretty new to Kafka and Redis.

Im trying to sink hash sets to Redis,but im not able to do so (its always written in as string).
Could it be that I didnt configure it right,or I missed something while setting up the connector?

**Comment by jcustenborder** [comment]
hi @pavlepiramida 

Sorry about the delay. I missed this issue. Can you post your config?

**Comment by pavlepiramida** [comment]
@jcustenborder there's no need to apologize!

Sadly,I just coudn't get it to work,so I migrated to confluent-kafka-dotnet as It was a bit easier to handle (both consuming and sinking) as a service with C#.

But if I do manage to dig up the sink conf,I will reopen the issue!
