### ISSUE TITLE
Could not initialize class io.lettuce.core.ClientOptions

### ISSUE THREAD

**Issue by oNddleo** [jcustenborder/kafka-connect-redis#36]
I have a problem when i created kafka connect redis:
`{"name":"sink","connector":{"state":"RUNNING","worker_id":"connect:8083"},"tasks":[{"id":0,"state":"FAILED","worker_id":"connect:8083","trace":"java.lang.NoClassDefFoundError: Could not initialize class io.lettuce.core.ClientOptions\n\tat com.github.jcustenborder.kafka.connect.redis.RedisSessionFactoryImpl$RedisSessionImpl.create(RedisSessionFactoryImpl.java:157)\n\tat com.github.jcustenborder.kafka.connect.redis.RedisSessionFactoryImpl.create(RedisSessionFactoryImpl.java:52)\n\tat com.github.jcustenborder.kafka.connect.redis.RedisSinkTask.start(RedisSinkTask.java:73)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:300)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:189)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n"}],"type":"sink"}`
I don't know that is error by library or my config of kafka connect redis.

**Comment by jcustenborder** [comment]
@oNddleo How did you do the install? You need to make sure that you have all of the dependencies as well. Easiest way to install is via the [Confluent Hub](https://www.confluent.io/hub/jcustenborder/kafka-connect-redis)

**Comment by oNddleo** [comment]
<img width="385" alt="Screen Shot 2021-07-23 at 08 56 20" src="https://user-images.githubusercontent.com/16056717/126729229-4da3b403-63eb-437c-8cef-d097fc66eedd.png">



> @oNddleo How did you do the install? You need to make sure that you have all of the dependencies as well. Easiest way to install is via the [Confluent Hub](https://www.confluent.io/hub/jcustenborder/kafka-connect-redis)

Yeah, I sure that your repository i download and it called by docker

**Comment by jcustenborder** [comment]
Can you post more info about your docker file? Here are a couple examples of how I do do the install. The big key is to ensure that the plugin path is correct. 

https://github.com/jcustenborder/cp-kafka-connect/blob/6.1.0/Dockerfile#L22
https://github.com/jcustenborder/cp-server-connect-operator/blob/6.1.0/Dockerfile#L22

**Comment by oNddleo** [comment]
> Can you post more info about your docker file? Here are a couple examples of how I do do the install. The big key is to ensure that the plugin path is correct.
> 
> https://github.com/jcustenborder/cp-kafka-connect/blob/6.1.0/Dockerfile#L22
> https://github.com/jcustenborder/cp-server-connect-operator/blob/6.1.0/Dockerfile#L22

Thanks, I will retry.
I checked it inside `/usr/share/confluent-hub-components` but when i create sinkconnector with curl so above exception

**Comment by oNddleo** [comment]
<img width="739" alt="Screen Shot 2021-07-23 at 09 09 49" src="https://user-images.githubusercontent.com/16056717/126729902-63aa85ca-8236-45f6-a075-4cf7d654ae15.png">
That's my Dockerfile, i use kafka redis and mongo connector all of us, kafka mongo connector successed but redis not, so I not found reason.

**Comment by jcustenborder** [comment]
Interesting. What happens if you use a later version of cp-kafka-connect?

**Comment by oNddleo** [comment]
> Interesting. What happens if you use a later version of cp-kafka-connect?

My bad not trying another version. Thanks your reply. I will try this.

**Comment by oNddleo** [comment]
> Interesting. What happens if you use a later version of cp-kafka-connect?
Thanks you very much. I fix that with later version.
