### ISSUE TITLE
Can't post topic to Kafka

### ISSUE THREAD

**Issue by oNddleo** [jcustenborder/kafka-connect-redis#37]
I created sink kafka-redis-connect.
I had post 
`curl --request POST \
    --header 'content-type: application/json' \
    --data '{
        "name": "sink",
        "config": {
            "connector.class" : "com.github.jcustenborder.kafka.connect.redis.RedisSinkConnector",
            "topics" : "test",
            "tasks.max" : "1",
            "key.converter" : "org.apache.kafka.connect.storage.StringConverter",
            "value.converter" : "org.apache.kafka.connect.storage.StringConverter"
            "redis.hosts":"redis:6379",
            "redis.cluster": true
        }
    }'`
But When I create `SET "test" 1` -> Inside Kafka topic nothing.
I don't know redis need set another config or kafka need set anything.
Can you help me? Thanks!

**Comment by jcustenborder** [comment]
This is a sink connector. It reads data from Kafka, and writes the data to Redis.
