### ISSUE TITLE
Kafka-connect-redis

### ISSUE THREAD

**Issue by kawi3** [jcustenborder/kafka-connect-redis#4]
Hallo ,

i'm trying to work with your connector but when i run it i get the following Exception
![image](https://user-images.githubusercontent.com/25535797/40786517-7fedc18c-64eb-11e8-85b0-5c44d13b8db4.png)
i'm sending JSON data to the topic
Hope you can help me

Thank you

**Comment by jcustenborder** [comment]
@kawi3 Sorry for the really long delay here. You can use the ByteArrayConverter to do this.
